### ISSUE TITLE
Setup a CI pipeline

### ISSUE THREAD

**Issue by KranthiGV** [jmairal/arsenic#11]
This item is to track setting up a continuous integration pipeline for cyanure (following the discussion in #10).

**Comment by KranthiGV** [comment]
We will have to decide a few things which will help us determine the build matrix.
What all variations we should build with? Some options are:
i) Operating systems: Ubuntu, OSX and Windows (Priority: High)
ii) Python versions: a few supported versions (Priority: Medium)
iii) Package manager for dependency installation -- such as conda or pip (Priority: Medium-Low)
iv) Type of configurations -- with mkl/openblas and with/without openmp (Priority: High)

**Comment by KranthiGV** [comment]
Additionally, we have to decide which CI provider do we use? Some options are github actions, circle ci, jenkins, azure pipelines, etc. 

My recommendation is to use Github Actions for now -- mainly for ease of integration. I have an example where I setup CI such that an Ubuntu/Python3.6/OpenBLAS/No_OpenMP build is built with each pull request or push to master. The pipeline definition is [here](https://github.com/KranthiGV/cyanure/blob/master/.github/workflows/python-package.yml) and a sample run can be seen [here](https://github.com/KranthiGV/cyanure/runs/950430570?check_suite_focus=true).

What do you think, @jmairal? If it sounds good, I will go about working on setting up a pipeline targeting a few configurations to begin with and we can enhance it later appropriately.

**Comment by jmairal** [comment]
Hi, 

- I am not familiar with CI's frameworks, and I would target the simplest one. Perhaps github action is good if it is already available within github.

Regarding the variations you mention 
  - the current code should be already compatible with Python 3.x and I think we can drop Python 2's support. 
  - the code has been tried successfully on  Ubunbu / CentOS / OSX and Windows10, but there is some work to do to make installation scripts that work on any machine without pain, especially for non-ubuntu machines. 
  - related to the previous point, it would be very nice to be able to install cyanure on any platform by a simple pip install  (or conda install).  One way to achieve this would be to provide pre-compiled packages as very often issues come from compilation time. I had a quick look at manylinux, but I do not understand a word of it (and I do not have enough time available to invest on it). I think that this is what scikit-learn people are using.

**Comment by KranthiGV** [comment]
You're right about utilising Github actions and that's my recommendation to
begin as well.

I'll get started based on the recommendations made. I'll aim to have the
basic infra ready by tomorrow and raise a PR.

Thanks
Kranthi

**Comment by thomasryck** [comment]
There is a Ci pipeline.  If you want to discuss the actual pipeline please open a new issue. I am closing the related PR.
