### ISSUE TITLE
Feature Request: optimization with L1 + L2,1 norm

### ISSUE THREAD

**Issue by eurunuela** [jmairal/arsenic#4]
Hi,

This package is awesome and I'm really looking forward to using it. However, the mathematical formulation I'm working with involves solving the regularization problem with an L1 + L2,1 regularization. You can find the proximal method implementation [here](https://hal.archives-ouvertes.fr/hal-00621044/document).

Given that I work with a multivariate model, solving the problem is computationally heavy, especially with Python. Do you think this could be implemented in cyanure?

Thanks!

**Comment by jmairal** [comment]
I can easily add this (will probably do it next week), but without the computation of duality gaps, meaning the stopping criterion will be different.

**Comment by eurunuela** [comment]
As long as the regularization is L1 + L2,1 there should be no problem. I would’ve loved to add it on my own but my C++ skills are not quite there. 

Thank you very much!

**Comment by jmairal** [comment]
Hi,

I have added this feature in Cyanure 0.2 (now available on pip) and also coded an algorithm to compute the duality gap with such a penalty. Note that the computation of the proximal operator was introduced in http://jmlr.csail.mit.edu/papers/volume12/jenatton11a/jenatton11a.pdf

Do not hesitate to tell me if you have difficulties to use it.

Best

**Comment by eurunuela** [comment]
Thank you very much. It will be fun using it and I hope we can make cool things work with it. Really appreciate it 🙌🏻
